### ISSUE TITLE
`tap-exchangeratesapi | target-csv` doesn't produce a `exchange_rates.csv` file

### ISSUE THREAD

**Issue by tjwaterman99** [singer-io/tap-exchangeratesapi#9]
I'm trying to run the example from the singer.io homepage:

```
tap-exchangeratesapi | target-csv
```

But there's no `exchange_rates.csv` file produced like in the example.

Running just the `tap-exchangeratesapi` itself gives this:

```
INFO Replicating exchange rate data from 2020-10-07 using base USD
{"type": "SCHEMA", "stream": "exchange_rate", "schema": {"type": "object", "properties": {"date": {"type": "string", "format": "date-time"}, "CAD": {"type": ["null", "number"]}, "HKD": {"type": ["null", "number"]}, "ISK": {"type": ["null", "number"]}, "PHP": {"type": ["null", "number"]}, "DKK": {"type": ["null", "number"]}, "HUF": {"type": ["null", "number"]}, "CZK": {"type": ["null", "number"]}, "GBP": {"type": ["null", "number"]}, "RON": {"type": ["null", "number"]}, "SEK": {"type": ["null", "number"]}, "IDR": {"type": ["null", "number"]}, "INR": {"type": ["null", "number"]}, "BRL": {"type": ["null", "number"]}, "RUB": {"type": ["null", "number"]}, "HRK": {"type": ["null", "number"]}, "JPY": {"type": ["null", "number"]}, "THB": {"type": ["null", "number"]}, "CHF": {"type": ["null", "number"]}, "EUR": {"type": ["null", "number"]}, "MYR": {"type": ["null", "number"]}, "BGN": {"type": ["null", "number"]}, "TRY": {"type": ["null", "number"]}, "CNY": {"type": ["null", "number"]}, "NOK": {"type": ["null", "number"]}, "NZD": {"type": ["null", "number"]}, "ZAR": {"type": ["null", "number"]}, "USD": {"type": ["null", "number"]}, "MXN": {"type": ["null", "number"]}, "SGD": {"type": ["null", "number"]}, "AUD": {"type": ["null", "number"]}, "ILS": {"type": ["null", "number"]}, "KRW": {"type": ["null", "number"]}, "PLN": {"type": ["null", "number"]}}}, "key_properties": ["date"]}
{"type": "STATE", "value": {"start_date": "2020-10-07"}}
INFO Tap exiting normally
```

Is there something I'm doing wrong from the example? Or could it be something about exchangeratesapi that has changed?

**Comment by tjwaterman99** [comment]
@cmerrick Not sure if you're still subscribed to this repo, so pinging you just in case.

**Comment by tjwaterman99** [comment]
Also, I'm getting a warning about the version of `singer-python` that's installed:

```
target-csv 0.3.0 requires singer-python==2.1.4, but you'll have singer-python 5.3.3 which is incompatible.
```

**Comment by dmosorast** [comment]
For the singer-python version issue, we [recommend to install the tap and target in different virtual environments](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-singer-with-python), due to the trouble that can arise managing dependencies across all taps and targets.

For the empty output, the ExchangeRatesAPI only posts "today's" values later in the day, so that's likely what happened here. If you run the tap like `tap-exchangeratesapi --config config.json` where config.json is a file with `{"start_date": "2020-10-06"}`, you will get yesterday's data. I might be off on that date format, so it might need to be ISO-8601 (`2020-10-06T00:00:00Z`)

**Comment by tjwaterman99** [comment]
Thanks @dmosorast! I'll close this out.

**Comment by drusellers** [comment]
So, your whole premise on your homepage is broken as is with out this config json. 🤔
